# Generated by Django 4.2.5 on 2023-12-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='userimage')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('materils', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='testapp.product_details')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='testapp.product_details')),
            ],
        ),
    ]
