# Generated by Django 4.2.5 on 2023-12-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='materils',
            new_name='materil',
        ),
    ]
